name: phpstan

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
  push:
    branches:
      - develop

jobs:
  phpstan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t menu-staging .

    - name: Run PHPStan
      run: |
        docker run -v ${{ github.workspace }}:/var/www/html my-laravel-app vendor/bin/phpstan analyse
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
    

